name: wechat_assets_picker
description: An audio/video/image picker in pure Dart which is the same with WeChat, support multi picking.
version: 6.2.0
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^4.1.0
  photo_manager: ^1.3.3
  provider: ^6.0.0
  video_player: ^2.1.14
  image_crop: ^0.4.0
